// AUTO-GENERATED from "Main Feed library .xlsx" (NDDB INAPH feed library).
// Nutrient values are grams per kg of feed on fresh (as-fed) basis.
// rate = default market price in Rs/kg (farmer can override).

export type FeedCategory = "roughage" | "concentrate" | "mineral";

export interface FeedItem {
  id: string;
  name: string;
  group: string;
  category: FeedCategory;
  /** Default price Rs per kg fresh */
  rate: number;
  /** g dry matter per kg fresh */
  dm: number;
  /** g TDN per kg fresh */
  tdn: number;
  /** g crude protein per kg fresh */
  cp: number;
  /** g calcium per kg fresh */
  ca: number;
  /** g phosphorus per kg fresh */
  p: number;
}

export const FEED_LIBRARY: FeedItem[] = [
  {
    "id": "maize_bran",
    "name": "Maize Bran",
    "group": "Bran",
    "category": "concentrate",
    "rate": 7.0,
    "dm": 900.0,
    "tdn": 540.0,
    "cp": 99.0,
    "ca": 1.728,
    "p": 2.268
  },
  {
    "id": "bengal_gram_bran",
    "name": "Bengal Gram Bran",
    "group": "Bran",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 495.0,
    "cp": 36.0,
    "ca": 0.864,
    "p": 1.944
  },
  {
    "id": "wheat_bran",
    "name": "Wheat Bran",
    "group": "Bran",
    "category": "concentrate",
    "rate": 11.0,
    "dm": 900.0,
    "tdn": 585.0,
    "cp": 144.0,
    "ca": 1.08,
    "p": 3.996
  },
  {
    "id": "maize_bran_hm",
    "name": "Maize Bran (HM)",
    "group": "Bran",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 310.0,
    "tdn": 186.0,
    "cp": 34.1,
    "ca": 0.595,
    "p": 0.673
  },
  {
    "id": "rice_bran__16%_oil",
    "name": "Rice Bran- 16% oil",
    "group": "Bran",
    "category": "concentrate",
    "rate": 10.0,
    "dm": 900.0,
    "tdn": 765.0,
    "cp": 126.0,
    "ca": 0.432,
    "p": 6.804
  },
  {
    "id": "rice_bran_deoiled",
    "name": "Rice Bran Deoiled",
    "group": "Bran",
    "category": "concentrate",
    "rate": 9.0,
    "dm": 900.0,
    "tdn": 540.0,
    "cp": 153.0,
    "ca": 0.432,
    "p": 5.724
  },
  {
    "id": "blackgram_chunni",
    "name": "Blackgram Chunni",
    "group": "Chunni",
    "category": "concentrate",
    "rate": 7.0,
    "dm": 900.0,
    "tdn": 540.0,
    "cp": 153.0,
    "ca": 1.944,
    "p": 1.296
  },
  {
    "id": "red_gram_chunni",
    "name": "Red gram chunni",
    "group": "Chunni",
    "category": "concentrate",
    "rate": 11.0,
    "dm": 900.0,
    "tdn": 540.0,
    "cp": 153.0,
    "ca": 2.16,
    "p": 1.26
  },
  {
    "id": "tur_chunni",
    "name": "Tur Chunni",
    "group": "Chunni",
    "category": "concentrate",
    "rate": 18.0,
    "dm": 900.0,
    "tdn": 540.0,
    "cp": 165.0,
    "ca": 1.776,
    "p": 0.648
  },
  {
    "id": "babul_seed_chunni",
    "name": "Babul seed chunni",
    "group": "Chunni",
    "category": "concentrate",
    "rate": 6.0,
    "dm": 900.0,
    "tdn": 495.0,
    "cp": 144.0,
    "ca": 3.888,
    "p": 0.864
  },
  {
    "id": "masoor_chunni",
    "name": "Masoor Chunni",
    "group": "Chunni",
    "category": "concentrate",
    "rate": 8.0,
    "dm": 900.0,
    "tdn": 540.0,
    "cp": 171.0,
    "ca": 2.16,
    "p": 1.296
  },
  {
    "id": "mung_chunni",
    "name": "Mung Chunni",
    "group": "Chunni",
    "category": "concentrate",
    "rate": 9.0,
    "dm": 900.0,
    "tdn": 540.0,
    "cp": 177.0,
    "ca": 2.376,
    "p": 1.944
  },
  {
    "id": "urd_chunni",
    "name": "Urd Chunni",
    "group": "Chunni",
    "category": "concentrate",
    "rate": 18.0,
    "dm": 900.0,
    "tdn": 540.0,
    "cp": 180.0,
    "ca": 0.78,
    "p": 0.384
  },
  {
    "id": "greengram_chunni",
    "name": "Greengram chunni",
    "group": "Chunni",
    "category": "concentrate",
    "rate": 8.0,
    "dm": 900.0,
    "tdn": 540.0,
    "cp": 153.0,
    "ca": 2.64,
    "p": 0.9
  },
  {
    "id": "bengalgram_chunni",
    "name": "Bengalgram chunni",
    "group": "Chunni",
    "category": "concentrate",
    "rate": 9.0,
    "dm": 900.0,
    "tdn": 594.0,
    "cp": 135.0,
    "ca": 1.632,
    "p": 0.9
  },
  {
    "id": "banas_hyprodaan",
    "name": "Banas Hyprodaan",
    "group": "Compound Feed",
    "category": "concentrate",
    "rate": 17.0,
    "dm": 900.0,
    "tdn": 650.0,
    "cp": 198.0,
    "ca": 3.6,
    "p": 2.16
  },
  {
    "id": "kmf_bypass_protein_feed",
    "name": "KMF Bypass protein feed",
    "group": "Compound Feed",
    "category": "concentrate",
    "rate": 12.0,
    "dm": 900.0,
    "tdn": 648.0,
    "cp": 225.0,
    "ca": 3.6,
    "p": 2.7
  },
  {
    "id": "cattle_feed_bis_ii",
    "name": "Cattle feed BIS-II",
    "group": "Compound Feed",
    "category": "concentrate",
    "rate": 15.0,
    "dm": 900.0,
    "tdn": 585.0,
    "cp": 180.0,
    "ca": 3.6,
    "p": 2.7
  },
  {
    "id": "cattle_feed_bis_i",
    "name": "Cattle feed BIS-I",
    "group": "Compound Feed",
    "category": "concentrate",
    "rate": 16.0,
    "dm": 900.0,
    "tdn": 648.0,
    "cp": 198.0,
    "ca": 3.6,
    "p": 2.7
  },
  {
    "id": "bypass_protein_feed",
    "name": "Bypass protein feed",
    "group": "Compound Feed",
    "category": "concentrate",
    "rate": 17.0,
    "dm": 900.0,
    "tdn": 648.0,
    "cp": 225.0,
    "ca": 3.6,
    "p": 2.7
  },
  {
    "id": "buffalo_feed",
    "name": "Buffalo feed",
    "group": "Compound Feed",
    "category": "concentrate",
    "rate": 12.0,
    "dm": 900.0,
    "tdn": 675.0,
    "cp": 198.0,
    "ca": 6.3,
    "p": 6.3
  },
  {
    "id": "samrudhi_dan_cattle_feed mehsana",
    "name": "Samrudhi Dan( Cattle feed) Mehsana",
    "group": "Compound Feed",
    "category": "concentrate",
    "rate": 13.5,
    "dm": 900.0,
    "tdn": 675.0,
    "cp": 198.0,
    "ca": 2.88,
    "p": 1.35
  },
  {
    "id": "kmf_cattle_feed",
    "name": "KMF Cattle feed",
    "group": "Compound Feed",
    "category": "concentrate",
    "rate": 11.0,
    "dm": 900.0,
    "tdn": 585.0,
    "cp": 180.0,
    "ca": 3.6,
    "p": 2.7
  },
  {
    "id": "calf_feed",
    "name": "Calf feed",
    "group": "Compound Feed",
    "category": "concentrate",
    "rate": 20.0,
    "dm": 900.0,
    "tdn": 675.0,
    "cp": 207.0,
    "ca": 7.2,
    "p": 6.3
  },
  {
    "id": "cattle_feed_below_bis",
    "name": "Cattle feed below BIS",
    "group": "Compound Feed",
    "category": "concentrate",
    "rate": 10.0,
    "dm": 900.0,
    "tdn": 495.0,
    "cp": 162.0,
    "ca": 3.6,
    "p": 2.7
  },
  {
    "id": "cattle_feed_high_protein",
    "name": "Cattle Feed High Protein",
    "group": "Compound Feed",
    "category": "concentrate",
    "rate": 22.0,
    "dm": 900.0,
    "tdn": 720.0,
    "cp": 225.0,
    "ca": 3.6,
    "p": 2.7
  },
  {
    "id": "soyabean_meal",
    "name": "Soyabean meal",
    "group": "DOC/Meal",
    "category": "concentrate",
    "rate": 19.0,
    "dm": 900.0,
    "tdn": 720.0,
    "cp": 477.0,
    "ca": 1.404,
    "p": 2.7
  },
  {
    "id": "kardi_meal",
    "name": "Kardi Meal",
    "group": "DOC/Meal",
    "category": "concentrate",
    "rate": 7.0,
    "dm": 900.0,
    "tdn": 495.0,
    "cp": 207.0,
    "ca": 1.296,
    "p": 2.592
  },
  {
    "id": "sunflower_meal",
    "name": "Sunflower meal",
    "group": "DOC/Meal",
    "category": "concentrate",
    "rate": 14.0,
    "dm": 900.0,
    "tdn": 594.0,
    "cp": 279.0,
    "ca": 2.16,
    "p": 3.996
  },
  {
    "id": "coconut_meal",
    "name": "Coconut meal",
    "group": "DOC/Meal",
    "category": "concentrate",
    "rate": 8.0,
    "dm": 900.0,
    "tdn": 648.0,
    "cp": 270.0,
    "ca": 0.972,
    "p": 2.16
  },
  {
    "id": "maize_gluten",
    "name": "Maize Gluten",
    "group": "DOC/Meal",
    "category": "concentrate",
    "rate": 10.0,
    "dm": 900.0,
    "tdn": 720.0,
    "cp": 522.0,
    "ca": 0.324,
    "p": 1.944
  },
  {
    "id": "gnut_meal",
    "name": "G.nut meal",
    "group": "DOC/Meal",
    "category": "concentrate",
    "rate": 12.0,
    "dm": 900.0,
    "tdn": 702.0,
    "cp": 396.0,
    "ca": 1.188,
    "p": 2.592
  },
  {
    "id": "rapeseed_meal",
    "name": "Rapeseed meal",
    "group": "DOC/Meal",
    "category": "concentrate",
    "rate": 12.0,
    "dm": 900.0,
    "tdn": 666.0,
    "cp": 378.0,
    "ca": 4.752,
    "p": 3.672
  },
  {
    "id": "guar_korma",
    "name": "Guar korma",
    "group": "DOC/Meal",
    "category": "concentrate",
    "rate": 12.0,
    "dm": 900.0,
    "tdn": 720.0,
    "cp": 486.0,
    "ca": 2.376,
    "p": 1.944
  },
  {
    "id": "cottonseed_meal",
    "name": "Cottonseed meal",
    "group": "DOC/Meal",
    "category": "concentrate",
    "rate": 11.0,
    "dm": 900.0,
    "tdn": 702.0,
    "cp": 369.0,
    "ca": 1.296,
    "p": 2.808
  },
  {
    "id": "guar_meal",
    "name": "Guar Meal",
    "group": "DOC/Meal",
    "category": "concentrate",
    "rate": 9.0,
    "dm": 900.0,
    "tdn": 675.0,
    "cp": 450.0,
    "ca": 2.376,
    "p": 1.944
  },
  {
    "id": "palm_kernel_meal",
    "name": "Palm kernel meal",
    "group": "DOC/Meal",
    "category": "concentrate",
    "rate": 8.0,
    "dm": 900.0,
    "tdn": 540.0,
    "cp": 180.0,
    "ca": 1.512,
    "p": 1.944
  },
  {
    "id": "maize_cake",
    "name": "Maize Cake",
    "group": "DOC/Meal",
    "category": "concentrate",
    "rate": 20.0,
    "dm": 900.0,
    "tdn": 720.0,
    "cp": 216.0,
    "ca": 2.484,
    "p": 5.616
  },
  {
    "id": "rice_bhardo__broken",
    "name": "Rice Bhardo/ Broken",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 9.0,
    "dm": 900.0,
    "tdn": 730.0,
    "cp": 87.0,
    "ca": 0.12,
    "p": 1.2
  },
  {
    "id": "bengalgram_grain",
    "name": "Bengalgram grain",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 30.0,
    "dm": 900.0,
    "tdn": 675.0,
    "cp": 162.0,
    "ca": 1.128,
    "p": 1.32
  },
  {
    "id": "black_gram",
    "name": "Black gram",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 25.0,
    "dm": 900.0,
    "tdn": 680.0,
    "cp": 23.7,
    "ca": 2.64,
    "p": 5.88
  },
  {
    "id": "taramira_seed",
    "name": "Taramira seed",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 23.0,
    "dm": 950.0,
    "tdn": 880.0,
    "cp": 280.0,
    "ca": 1.56,
    "p": 2.7
  },
  {
    "id": "dhaincha_seeds_sesbania",
    "name": "Dhaincha seeds (Sesbania)",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 30.0,
    "dm": 900.0,
    "tdn": 581.0,
    "cp": 309.0,
    "ca": 1.056,
    "p": 2.736
  },
  {
    "id": "bajra_bhardo_broken",
    "name": "Bajra bhardo/broken",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 7.5,
    "dm": 900.0,
    "tdn": 616.0,
    "cp": 80.0,
    "ca": 0.348,
    "p": 1.188
  },
  {
    "id": "maize_bhardo_broken",
    "name": "Maize bhardo/broken",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 10.0,
    "dm": 900.0,
    "tdn": 713.0,
    "cp": 85.0,
    "ca": 0.132,
    "p": 1.068
  },
  {
    "id": "wheat_bhardo_broken",
    "name": "Wheat bhardo/broken",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 9.0,
    "dm": 900.0,
    "tdn": 697.0,
    "cp": 117.0,
    "ca": 0.348,
    "p": 1.296
  },
  {
    "id": "greengram",
    "name": "Greengram",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 25.0,
    "dm": 900.0,
    "tdn": 690.0,
    "cp": 258.0,
    "ca": 1.92,
    "p": 5.4
  },
  {
    "id": "soya_seeds",
    "name": "Soya seeds",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 24.0,
    "dm": 900.0,
    "tdn": 820.0,
    "cp": 378.0,
    "ca": 1.596,
    "p": 2.208
  },
  {
    "id": "ragi_grain",
    "name": "Ragi grain",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 9.0,
    "dm": 900.0,
    "tdn": 700.0,
    "cp": 90.0,
    "ca": 0.48,
    "p": 0.324
  },
  {
    "id": "barley_bhardo__broken",
    "name": "Barley Bhardo/ Broken",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 10.0,
    "dm": 900.0,
    "tdn": 710.0,
    "cp": 108.0,
    "ca": 0.324,
    "p": 1.56
  },
  {
    "id": "horse_gram_grain",
    "name": "Horse gram grain",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 35.0,
    "dm": 900.0,
    "tdn": 675.0,
    "cp": 198.0,
    "ca": 1.296,
    "p": 0.492
  },
  {
    "id": "cowpea_seed",
    "name": "Cowpea Seed",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 20.0,
    "dm": 900.0,
    "tdn": 594.0,
    "cp": 240.0,
    "ca": 0.468,
    "p": 1.8
  },
  {
    "id": "methi_seeds_fenugreek",
    "name": "Methi Seeds (Fenugreek)",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 30.0,
    "dm": 900.0,
    "tdn": 607.0,
    "cp": 240.0,
    "ca": 1.056,
    "p": 1.98
  },
  {
    "id": "whole_cotton_seed",
    "name": "Whole Cotton Seed",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 10.0,
    "dm": 900.0,
    "tdn": 810.0,
    "cp": 198.0,
    "ca": 1.512,
    "p": 4.104
  },
  {
    "id": "blackgram_grain",
    "name": "Blackgram grain",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 20.0,
    "dm": 900.0,
    "tdn": 702.0,
    "cp": 261.0,
    "ca": 0.648,
    "p": 1.188
  },
  {
    "id": "jowar_grain",
    "name": "Jowar grain",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 8.0,
    "dm": 900.0,
    "tdn": 720.0,
    "cp": 78.0,
    "ca": 0.216,
    "p": 1.08
  },
  {
    "id": "rice_grain",
    "name": "Rice grain",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 9.0,
    "dm": 900.0,
    "tdn": 738.0,
    "cp": 81.0,
    "ca": 0.108,
    "p": 1.188
  },
  {
    "id": "barley_grain",
    "name": "Barley Grain",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 9.0,
    "dm": 900.0,
    "tdn": 711.0,
    "cp": 108.0,
    "ca": 0.324,
    "p": 1.62
  },
  {
    "id": "oat_grain",
    "name": "Oat Grain",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 8.0,
    "dm": 900.0,
    "tdn": 657.0,
    "cp": 99.0,
    "ca": 0.432,
    "p": 1.296
  },
  {
    "id": "wheat_grain",
    "name": "Wheat grain",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 10.0,
    "dm": 900.0,
    "tdn": 774.0,
    "cp": 99.0,
    "ca": 0.216,
    "p": 1.188
  },
  {
    "id": "bajra_grain",
    "name": "Bajra grain",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 9.0,
    "dm": 900.0,
    "tdn": 684.0,
    "cp": 108.0,
    "ca": 0.54,
    "p": 1.62
  },
  {
    "id": "maize_grain",
    "name": "Maize grain",
    "group": "Grain/Seed",
    "category": "concentrate",
    "rate": 11.0,
    "dm": 900.0,
    "tdn": 792.0,
    "cp": 81.0,
    "ca": 0.108,
    "p": 1.512
  },
  {
    "id": "grass_guinea",
    "name": "Grass Guinea",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 22.0,
    "ca": 0.624,
    "p": 0.24
  },
  {
    "id": "grass_hybrid_napier",
    "name": "Grass Hybrid Napier",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 20.0,
    "ca": 0.648,
    "p": 0.24
  },
  {
    "id": "grass_rye",
    "name": "Grass Rye",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 20.0,
    "ca": 0.408,
    "p": 0.168
  },
  {
    "id": "begharo_grass",
    "name": "Begharo Grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.5,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 30.0,
    "ca": 1.968,
    "p": 0.288
  },
  {
    "id": "grass_elephant",
    "name": "Grass Elephant",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 12.0,
    "ca": 0.48,
    "p": 0.192
  },
  {
    "id": "grass_para",
    "name": "Grass Para",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 104.0,
    "cp": 22.0,
    "ca": 0.336,
    "p": 0.144
  },
  {
    "id": "guar_grass",
    "name": "Guar Grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.5,
    "dm": 200.0,
    "tdn": 104.0,
    "cp": 24.0,
    "ca": 2.736,
    "p": 0.204
  },
  {
    "id": "grass__sorg_sudan",
    "name": "Grass- Sorg. Sudan",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.5,
    "dm": 300.0,
    "tdn": 165.0,
    "cp": 24.0,
    "ca": 1.548,
    "p": 1.476
  },
  {
    "id": "dhaman_grass",
    "name": "Dhaman Grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.5,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 8.0,
    "ca": 5.28,
    "p": 0.144
  },
  {
    "id": "grasses",
    "name": "Grasses",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 8.0,
    "ca": 0.384,
    "p": 0.144
  },
  {
    "id": "gandhir_grass",
    "name": "Gandhir Grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.5,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 16.0,
    "ca": 1.248,
    "p": 0.6
  },
  {
    "id": "lano_grass",
    "name": "Lano Grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.5,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 30.0,
    "ca": 1.512,
    "p": 0.336
  },
  {
    "id": "lamp_grass",
    "name": "Lamp Grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.5,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 12.0,
    "ca": 0.504,
    "p": 0.192
  },
  {
    "id": "dhrabal_grass",
    "name": "Dhrabal Grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.5,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 16.0,
    "ca": 1.032,
    "p": 0.144
  },
  {
    "id": "puyadi_grass",
    "name": "Puyadi Grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.5,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 10.0,
    "ca": 0.72,
    "p": 0.12
  },
  {
    "id": "liyar_grass",
    "name": "Liyar Grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.5,
    "dm": 200.0,
    "tdn": 104.0,
    "cp": 24.0,
    "ca": 2.736,
    "p": 0.24
  },
  {
    "id": "uein_grass",
    "name": "Uein Grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.5,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 32.0,
    "ca": 3.24,
    "p": 0.36
  },
  {
    "id": "liber_waker_grass",
    "name": "Liber Waker Grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.5,
    "dm": 200.0,
    "tdn": 104.0,
    "cp": 20.0,
    "ca": 10.992,
    "p": 0.216
  },
  {
    "id": "pillipesara",
    "name": "Pillipesara",
    "group": "Grass",
    "category": "roughage",
    "rate": 1.0,
    "dm": 200.0,
    "tdn": 112.62,
    "cp": 33.28,
    "ca": 1.814,
    "p": 0.209
  },
  {
    "id": "rhodes_grass",
    "name": "Rhodes grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 16.0,
    "ca": 0.252,
    "p": 0.24
  },
  {
    "id": "johnson_grass",
    "name": "Johnson grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 113.94,
    "cp": 16.9,
    "ca": 0.48,
    "p": 0.23
  },
  {
    "id": "deer_grass",
    "name": "Deer Grass",
    "group": "Grass",
    "category": "roughage",
    "rate": 0.5,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 16.0,
    "ca": 0.72,
    "p": 0.384
  },
  {
    "id": "wheat_fodder",
    "name": "Wheat Fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 1.25,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 15.0,
    "ca": 0.336,
    "p": 0.216
  },
  {
    "id": "barseem_fodder",
    "name": "Barseem Fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 1.2,
    "dm": 200.0,
    "tdn": 130.0,
    "cp": 34.0,
    "ca": 1.584,
    "p": 0.216
  },
  {
    "id": "mustard_fodder",
    "name": "Mustard Fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 1.2,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 18.0,
    "ca": 3.528,
    "p": 1.032
  },
  {
    "id": "bajra_fodder",
    "name": "Bajra Fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 16.0,
    "ca": 0.576,
    "p": 0.144
  },
  {
    "id": "barley_fodder",
    "name": "Barley fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 0.8,
    "dm": 250.0,
    "tdn": 120.0,
    "cp": 21.0,
    "ca": 0.588,
    "p": 0.24
  },
  {
    "id": "velvet_bean_fodder",
    "name": "Velvet bean fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 1.0,
    "dm": 300.0,
    "tdn": 180.0,
    "cp": 45.0,
    "ca": 2.376,
    "p": 0.648
  },
  {
    "id": "stylosanthes_fodder",
    "name": "Stylosanthes fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 1.2,
    "dm": 200.0,
    "tdn": 115.0,
    "cp": 24.0,
    "ca": 1.224,
    "p": 0.276
  },
  {
    "id": "sunflower_fodder",
    "name": "Sunflower Fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 1.2,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 22.0,
    "ca": 0.912,
    "p": 0.168
  },
  {
    "id": "ragi_fodder___leaves",
    "name": "Ragi fodder / leaves",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 104.0,
    "cp": 13.0,
    "ca": 0.576,
    "p": 0.492
  },
  {
    "id": "napier_bajra___nb_21",
    "name": "Napier Bajra / NB-21",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 1.25,
    "dm": 200.0,
    "tdn": 115.0,
    "cp": 16.0,
    "ca": 0.504,
    "p": 0.408
  },
  {
    "id": "oat_fodder",
    "name": "Oat Fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 120.0,
    "cp": 22.0,
    "ca": 0.408,
    "p": 0.192
  },
  {
    "id": "cowpea_fodder",
    "name": "Cowpea Fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 1.2,
    "dm": 200.0,
    "tdn": 130.0,
    "cp": 36.0,
    "ca": 1.368,
    "p": 0.216
  },
  {
    "id": "lucerne_fodder",
    "name": "Lucerne Fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 1.2,
    "dm": 200.0,
    "tdn": 130.0,
    "cp": 34.0,
    "ca": 1.872,
    "p": 0.264
  },
  {
    "id": "maize_fodder",
    "name": "Maize Fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 130.0,
    "cp": 15.0,
    "ca": 0.648,
    "p": 0.144
  },
  {
    "id": "jowar_fodder",
    "name": "Jowar Fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 16.0,
    "ca": 0.384,
    "p": 0.24
  },
  {
    "id": "paddy_fodder",
    "name": "Paddy Fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 12.0,
    "ca": 0.288,
    "p": 0.192
  },
  {
    "id": "horse_gram_fodder",
    "name": "Horse gram Fodder",
    "group": "Green Fodder",
    "category": "roughage",
    "rate": 1.2,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 30.0,
    "ca": 1.296,
    "p": 0.168
  },
  {
    "id": "berseem_hay",
    "name": "Berseem hay",
    "group": "Hay",
    "category": "roughage",
    "rate": 4.5,
    "dm": 900.0,
    "tdn": 495.0,
    "cp": 135.0,
    "ca": 12.96,
    "p": 1.62
  },
  {
    "id": "grass_hay",
    "name": "Grass Hay",
    "group": "Hay",
    "category": "roughage",
    "rate": 3.0,
    "dm": 900.0,
    "tdn": 432.0,
    "cp": 63.0,
    "ca": 2.7,
    "p": 1.08
  },
  {
    "id": "oats_hay",
    "name": "Oats Hay",
    "group": "Hay",
    "category": "roughage",
    "rate": 4.5,
    "dm": 900.0,
    "tdn": 477.0,
    "cp": 72.0,
    "ca": 1.944,
    "p": 1.512
  },
  {
    "id": "jowar_hay",
    "name": "Jowar Hay",
    "group": "Hay",
    "category": "roughage",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 450.0,
    "cp": 63.0,
    "ca": 5.4,
    "p": 3.24
  },
  {
    "id": "cowpea_hay",
    "name": "Cowpea Hay",
    "group": "Hay",
    "category": "roughage",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 477.0,
    "cp": 135.0,
    "ca": 15.12,
    "p": 3.78
  },
  {
    "id": "lucerne_hay",
    "name": "Lucerne Hay",
    "group": "Hay",
    "category": "roughage",
    "rate": 4.5,
    "dm": 900.0,
    "tdn": 495.0,
    "cp": 144.0,
    "ca": 12.96,
    "p": 1.728
  },
  {
    "id": "rhodes_grass_hay",
    "name": "Rhodes grass hay",
    "group": "Hay",
    "category": "roughage",
    "rate": 2.5,
    "dm": 900.0,
    "tdn": 460.0,
    "cp": 54.0,
    "ca": 1.68,
    "p": 0.72
  },
  {
    "id": "sun_hemp_hay",
    "name": "Sun hemp hay",
    "group": "Hay",
    "category": "roughage",
    "rate": 5.0,
    "dm": 900.0,
    "tdn": 497.83,
    "cp": 140.18,
    "ca": 5.64,
    "p": 0.744
  },
  {
    "id": "jowar_husk",
    "name": "Jowar husk",
    "group": "Husk",
    "category": "concentrate",
    "rate": 2.0,
    "dm": 900.0,
    "tdn": 450.0,
    "cp": 42.0,
    "ca": 0.96,
    "p": 0.288
  },
  {
    "id": "maize_husk",
    "name": "Maize Husk",
    "group": "Husk",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 468.0,
    "cp": 91.0,
    "ca": 1.8,
    "p": 2.88
  },
  {
    "id": "saunf_husk",
    "name": "Saunf Husk",
    "group": "Husk",
    "category": "concentrate",
    "rate": 2.0,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 81.0,
    "ca": 1.296,
    "p": 0.216
  },
  {
    "id": "ragi_husk",
    "name": "Ragi Husk",
    "group": "Husk",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 450.0,
    "cp": 40.0,
    "ca": 0.96,
    "p": 0.288
  },
  {
    "id": "isabgol_jeeraru",
    "name": "Isabgol (Jeeraru)",
    "group": "Husk",
    "category": "concentrate",
    "rate": 14.0,
    "dm": 900.0,
    "tdn": 675.0,
    "cp": 170.0,
    "ca": 1.2,
    "p": 2.28
  },
  {
    "id": "barley_husk",
    "name": "Barley Husk",
    "group": "Husk",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 450.0,
    "cp": 42.0,
    "ca": 0.96,
    "p": 0.288
  },
  {
    "id": "kodra_husk",
    "name": "Kodra Husk",
    "group": "Husk",
    "category": "concentrate",
    "rate": 3.0,
    "dm": 900.0,
    "tdn": 450.0,
    "cp": 72.0,
    "ca": 1.512,
    "p": 0.324
  },
  {
    "id": "pine_apple_leaves",
    "name": "Pine Apple Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.4,
    "dm": 400.0,
    "tdn": 180.0,
    "cp": 16.0,
    "ca": 2.112,
    "p": 0.432
  },
  {
    "id": "areca_sheath",
    "name": "Areca sheath",
    "group": "Leaves",
    "category": "roughage",
    "rate": 1.0,
    "dm": 200.0,
    "tdn": 98.6,
    "cp": 7.0,
    "ca": 0.96,
    "p": 0.192
  },
  {
    "id": "coconut_leaves",
    "name": "Coconut Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.4,
    "dm": 400.0,
    "tdn": 160.0,
    "cp": 28.0,
    "ca": 0.816,
    "p": 0.528
  },
  {
    "id": "eucalyptus_leaves",
    "name": "Eucalyptus Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.5,
    "dm": 300.0,
    "tdn": 150.0,
    "cp": 48.0,
    "ca": 2.184,
    "p": 0.396
  },
  {
    "id": "areca_leaves",
    "name": "Areca leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 1.0,
    "dm": 200.0,
    "tdn": 108.0,
    "cp": 8.0,
    "ca": 0.96,
    "p": 0.192
  },
  {
    "id": "scane_top_leaves",
    "name": "S.cane top/leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 2.0,
    "dm": 250.0,
    "tdn": 113.0,
    "cp": 8.0,
    "ca": 0.756,
    "p": 0.156
  },
  {
    "id": "anjan_leaves",
    "name": "Anjan Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 1.0,
    "dm": 300.0,
    "tdn": 150.0,
    "cp": 33.0,
    "ca": 2.58,
    "p": 0.15
  },
  {
    "id": "banana_leaves",
    "name": "Banana Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.4,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 24.0,
    "ca": 1.344,
    "p": 0.072
  },
  {
    "id": "palash_leaves",
    "name": "Palash leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.4,
    "dm": 400.0,
    "tdn": 450.0,
    "cp": 54.0,
    "ca": 10.2,
    "p": 0.3
  },
  {
    "id": "glyricidia_leaves",
    "name": "Glyricidia leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 40.0,
    "ca": 2.28,
    "p": 0.72
  },
  {
    "id": "chinese_cabbage",
    "name": "Chinese Cabbage",
    "group": "Leaves",
    "category": "roughage",
    "rate": 1.0,
    "dm": 150.0,
    "tdn": 75.0,
    "cp": 27.0,
    "ca": 1.368,
    "p": 0.144
  },
  {
    "id": "tapioca_leaves",
    "name": "Tapioca leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 92.0,
    "cp": 25.0,
    "ca": 2.4,
    "p": 1.92
  },
  {
    "id": "mulbery_leaves",
    "name": "Mulbery Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.4,
    "dm": 300.0,
    "tdn": 180.0,
    "cp": 66.0,
    "ca": 3.024,
    "p": 0.36
  },
  {
    "id": "chicory_leaves",
    "name": "Chicory Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.4,
    "dm": 150.0,
    "tdn": 78.0,
    "cp": 34.5,
    "ca": 0.852,
    "p": 0.216
  },
  {
    "id": "khejari_leaves",
    "name": "Khejari Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 2.0,
    "dm": 900.0,
    "tdn": 450.0,
    "cp": 144.0,
    "ca": 14.256,
    "p": 0.432
  },
  {
    "id": "neem_leaves",
    "name": "Neem Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.4,
    "dm": 200.0,
    "tdn": 80.0,
    "cp": 30.0,
    "ca": 2.4,
    "p": 0.168
  },
  {
    "id": "pipal_leaves",
    "name": "Pipal Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.4,
    "dm": 200.0,
    "tdn": 80.0,
    "cp": 14.0,
    "ca": 3.552,
    "p": 0.12
  },
  {
    "id": "anjawan_leaves",
    "name": "Anjawan Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.4,
    "dm": 200.0,
    "tdn": 90.0,
    "cp": 24.0,
    "ca": 1.152,
    "p": 0.288
  },
  {
    "id": "subabul_leaves",
    "name": "Subabul leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 1.5,
    "dm": 200.0,
    "tdn": 120.0,
    "cp": 44.0,
    "ca": 2.4,
    "p": 0.408
  },
  {
    "id": "babul_leaves",
    "name": "Babul Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.5,
    "dm": 200.0,
    "tdn": 120.0,
    "cp": 26.0,
    "ca": 1.68,
    "p": 0.264
  },
  {
    "id": "grape_leaves",
    "name": "Grape leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 2.0,
    "dm": 350.0,
    "tdn": 290.0,
    "cp": 20.0,
    "ca": 9.6,
    "p": 0.72
  },
  {
    "id": "mango_leaves",
    "name": "Mango Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.4,
    "dm": 200.0,
    "tdn": 80.0,
    "cp": 6.0,
    "ca": 2.592,
    "p": 0.048
  },
  {
    "id": "shewari___sesbania_leaves",
    "name": "Shewari / Sesbania Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 1.0,
    "dm": 200.0,
    "tdn": 104.0,
    "cp": 46.0,
    "ca": 8.64,
    "p": 0.72
  },
  {
    "id": "bamboo_leaves",
    "name": "Bamboo Leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 0.4,
    "dm": 200.0,
    "tdn": 80.0,
    "cp": 10.0,
    "ca": 0.672,
    "p": 0.048
  },
  {
    "id": "castor_leaves",
    "name": "Castor leaves",
    "group": "Leaves",
    "category": "roughage",
    "rate": 1.0,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 50.0,
    "ca": 4.8,
    "p": 0.144
  },
  {
    "id": "asmm_mathura",
    "name": "ASMM-Mathura",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 205.8,
    "p": 122.5
  },
  {
    "id": "asmm_jalgaon",
    "name": "ASMM-Jalgaon",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 215.6,
    "p": 107.8
  },
  {
    "id": "asmm_etawah",
    "name": "ASMM-Etawah",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 205.8,
    "p": 122.5
  },
  {
    "id": "asmm_chittoor",
    "name": "ASMM-Chittoor",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 230.3,
    "p": 122.5
  },
  {
    "id": "asmm_bihar",
    "name": "ASMM-Bihar",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 156.8,
    "p": 88.2
  },
  {
    "id": "asmm_bikaner",
    "name": "ASMM-Bikaner",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 220.5,
    "p": 137.2
  },
  {
    "id": "asmm_jodhpur",
    "name": "ASMM-Jodhpur",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 220.5,
    "p": 137.2
  },
  {
    "id": "asmm_meerut",
    "name": "ASMM-Meerut",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 196.0,
    "p": 122.5
  },
  {
    "id": "asmm_kolhapur",
    "name": "ASMM-Kolhapur",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 213.64,
    "p": 122.5
  },
  {
    "id": "asmm_moradabad",
    "name": "ASMM-Moradabad",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 215.6,
    "p": 127.4
  },
  {
    "id": "asmm_ajmer",
    "name": "ASMM-Ajmer",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 220.5,
    "p": 137.2
  },
  {
    "id": "asmm_dhaulpur",
    "name": "ASMM-Dhaulpur",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 210.7,
    "p": 146.02
  },
  {
    "id": "asmm_mehsana",
    "name": "ASMM-Mehsana",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 215.6,
    "p": 141.12
  },
  {
    "id": "asmm_surat",
    "name": "ASMM-Surat",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 225.4,
    "p": 137.2
  },
  {
    "id": "asmm_panchmahal",
    "name": "ASMM-Panchmahal",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 225.4,
    "p": 107.8
  },
  {
    "id": "asmm_anand",
    "name": "ASMM-Anand",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 215.6,
    "p": 137.2
  },
  {
    "id": "asmm_kaira",
    "name": "ASMM-Kaira",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 215.6,
    "p": 137.2
  },
  {
    "id": "asmm_kutch",
    "name": "ASMM-Kutch",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 205.8,
    "p": 135.24
  },
  {
    "id": "asmm_junagadh",
    "name": "ASMM-Junagadh",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 215.6,
    "p": 145.04
  },
  {
    "id": "asmm_udaipur",
    "name": "ASMM-Udaipur",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 220.5,
    "p": 137.2
  },
  {
    "id": "asmm_bharatpur",
    "name": "ASMM-Bharatpur",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 210.7,
    "p": 146.02
  },
  {
    "id": "mineral_mixture_bis",
    "name": "Mineral Mixture BIS",
    "group": "Minerals",
    "category": "mineral",
    "rate": 45.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 196.0,
    "p": 117.6
  },
  {
    "id": "asmm___western_up",
    "name": "ASMM - Western UP",
    "group": "Minerals",
    "category": "mineral",
    "rate": 60.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 250.0,
    "p": 118.0
  },
  {
    "id": "calcite_powder",
    "name": "Calcite powder",
    "group": "Minerals",
    "category": "mineral",
    "rate": 3.0,
    "dm": 900.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 370.0,
    "p": 0.0
  },
  {
    "id": "asmm_madhya_pradesh",
    "name": "ASMM Madhya Pradesh",
    "group": "Minerals",
    "category": "mineral",
    "rate": 55.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 259.0,
    "p": 98.0
  },
  {
    "id": "asmm_kerala",
    "name": "ASMM Kerala",
    "group": "Minerals",
    "category": "mineral",
    "rate": 70.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 220.0,
    "p": 125.0
  },
  {
    "id": "milma_min",
    "name": "MILMA MIN",
    "group": "Minerals",
    "category": "mineral",
    "rate": 56.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 220.0,
    "p": 125.0
  },
  {
    "id": "asmm_sabarkantha",
    "name": "ASMM-Sabarkantha",
    "group": "Minerals",
    "category": "mineral",
    "rate": 50.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 220.0,
    "p": 140.0
  },
  {
    "id": "liquid_calcium",
    "name": "Liquid Calcium",
    "group": "Minerals",
    "category": "mineral",
    "rate": 150.0,
    "dm": 450.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 15.75,
    "p": 7.87
  },
  {
    "id": "asmm___rajasthan",
    "name": "ASMM - Rajasthan",
    "group": "Minerals",
    "category": "mineral",
    "rate": 57.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 215.6,
    "p": 137.2
  },
  {
    "id": "asmm_bangalore",
    "name": "ASMM-Bangalore",
    "group": "Minerals",
    "category": "mineral",
    "rate": 40.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 192.0,
    "p": 90.0
  },
  {
    "id": "calsagar",
    "name": "Calsagar",
    "group": "Minerals",
    "category": "mineral",
    "rate": 140.0,
    "dm": 990.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 200.0,
    "p": 100.0
  },
  {
    "id": "asmm_banaskantha",
    "name": "ASMM-Banaskantha",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 215.6,
    "p": 141.12
  },
  {
    "id": "asmm_j_p_nagar",
    "name": "ASMM-J P Nagar",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 215.6,
    "p": 127.4
  },
  {
    "id": "asmm_agra",
    "name": "ASMM-Agra",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 205.8,
    "p": 122.5
  },
  {
    "id": "asmm_bulandshahr",
    "name": "ASMM-Bulandshahr",
    "group": "Minerals",
    "category": "mineral",
    "rate": 30.0,
    "dm": 980.0,
    "tdn": 0.0,
    "cp": 0.0,
    "ca": 215.6,
    "p": 122.5
  },
  {
    "id": "cotton_seed_cake",
    "name": "Cotton seed cake",
    "group": "Oil Cake",
    "category": "concentrate",
    "rate": 12.0,
    "dm": 900.0,
    "tdn": 720.0,
    "cp": 333.0,
    "ca": 0.756,
    "p": 1.296
  },
  {
    "id": "kardi_oil_cake",
    "name": "Kardi Oil Cake",
    "group": "Oil Cake",
    "category": "concentrate",
    "rate": 12.0,
    "dm": 900.0,
    "tdn": 523.0,
    "cp": 160.0,
    "ca": 5.4,
    "p": 4.32
  },
  {
    "id": "mustard_cake",
    "name": "Mustard cake",
    "group": "Oil Cake",
    "category": "concentrate",
    "rate": 14.0,
    "dm": 900.0,
    "tdn": 720.0,
    "cp": 324.0,
    "ca": 4.644,
    "p": 3.996
  },
  {
    "id": "sunflower_cake",
    "name": "Sunflower cake",
    "group": "Oil Cake",
    "category": "concentrate",
    "rate": 12.0,
    "dm": 900.0,
    "tdn": 648.0,
    "cp": 234.0,
    "ca": 2.052,
    "p": 3.996
  },
  {
    "id": "und_cottonseed_cake",
    "name": "Und. cottonseed cake",
    "group": "Oil Cake",
    "category": "concentrate",
    "rate": 11.0,
    "dm": 900.0,
    "tdn": 666.0,
    "cp": 216.0,
    "ca": 0.864,
    "p": 1.512
  },
  {
    "id": "rapeseed_cake",
    "name": "Rapeseed Cake",
    "group": "Oil Cake",
    "category": "concentrate",
    "rate": 14.0,
    "dm": 900.0,
    "tdn": 720.0,
    "cp": 342.0,
    "ca": 4.644,
    "p": 3.996
  },
  {
    "id": "linseed_oil_cake",
    "name": "Linseed oil Cake",
    "group": "Oil Cake",
    "category": "concentrate",
    "rate": 14.0,
    "dm": 900.0,
    "tdn": 648.0,
    "cp": 270.0,
    "ca": 2.592,
    "p": 5.184
  },
  {
    "id": "palm_kernel_oil_cake",
    "name": "Palm kernel oil Cake",
    "group": "Oil Cake",
    "category": "concentrate",
    "rate": 10.0,
    "dm": 900.0,
    "tdn": 549.0,
    "cp": 153.0,
    "ca": 1.512,
    "p": 1.944
  },
  {
    "id": "coconut_cake",
    "name": "Coconut Cake",
    "group": "Oil Cake",
    "category": "concentrate",
    "rate": 10.0,
    "dm": 900.0,
    "tdn": 738.0,
    "cp": 234.0,
    "ca": 1.944,
    "p": 2.7
  },
  {
    "id": "groundnut_cake",
    "name": "Groundnut cake",
    "group": "Oil Cake",
    "category": "concentrate",
    "rate": 17.0,
    "dm": 900.0,
    "tdn": 765.0,
    "cp": 360.0,
    "ca": 0.972,
    "p": 2.16
  },
  {
    "id": "til_cake",
    "name": "Til Cake",
    "group": "Oil Cake",
    "category": "concentrate",
    "rate": 16.0,
    "dm": 900.0,
    "tdn": 675.0,
    "cp": 360.0,
    "ca": 8.64,
    "p": 3.888
  },
  {
    "id": "karanj_cake",
    "name": "Karanj Cake",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 5.0,
    "dm": 900.0,
    "tdn": 540.0,
    "cp": 306.0,
    "ca": 3.996,
    "p": 2.268
  },
  {
    "id": "barley_brewery_waste",
    "name": "Barley Brewery Waste",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 8.0,
    "dm": 300.0,
    "tdn": 168.0,
    "cp": 72.0,
    "ca": 1.32,
    "p": 0.48
  },
  {
    "id": "sesame___gingelly_oil",
    "name": "Sesame / Gingelly oil",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 150.0,
    "dm": 999.0,
    "tdn": 1940.0,
    "cp": 0.0,
    "ca": 0.0,
    "p": 0.0
  },
  {
    "id": "whey_liquid",
    "name": "Whey liquid",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 1.0,
    "dm": 60.0,
    "tdn": 48.0,
    "cp": 7.2,
    "ca": 1.32,
    "p": 0.96
  },
  {
    "id": "molasses",
    "name": "Molasses",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 5.0,
    "dm": 820.0,
    "tdn": 492.0,
    "cp": 16.0,
    "ca": 2.364,
    "p": 0.888
  },
  {
    "id": "ragi_waste",
    "name": "Ragi waste",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 11.0,
    "dm": 890.0,
    "tdn": 523.8,
    "cp": 116.8,
    "ca": 0.6,
    "p": 0.384
  },
  {
    "id": "babul_pods",
    "name": "Babul Pods",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 5.0,
    "dm": 900.0,
    "tdn": 495.0,
    "cp": 108.0,
    "ca": 5.616,
    "p": 0.864
  },
  {
    "id": "brewery_waste_maize",
    "name": "Brewery waste maize",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 5.0,
    "dm": 350.0,
    "tdn": 259.0,
    "cp": 55.0,
    "ca": 0.096,
    "p": 0.18
  },
  {
    "id": "mahua_cake",
    "name": "Mahua Cake",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 5.0,
    "dm": 900.0,
    "tdn": 540.0,
    "cp": 189.0,
    "ca": 0.648,
    "p": 1.944
  },
  {
    "id": "tamarind_seed_powder",
    "name": "Tamarind Seed Powder",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 576.0,
    "cp": 108.0,
    "ca": 1.62,
    "p": 0.972
  },
  {
    "id": "spent_pepper_waste",
    "name": "Spent Pepper Waste",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 3.0,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 117.0,
    "ca": 1.944,
    "p": 0.54
  },
  {
    "id": "tapioca_starch_waste",
    "name": "Tapioca Starch Waste",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 576.0,
    "cp": 108.0,
    "ca": 1.62,
    "p": 0.972
  },
  {
    "id": "ambadi_cake",
    "name": "Ambadi Cake",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 7.0,
    "dm": 900.0,
    "tdn": 540.0,
    "cp": 211.0,
    "ca": 1.728,
    "p": 2.484
  },
  {
    "id": "brewery_waste_wheat",
    "name": "Brewery waste wheat",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 250.0,
    "tdn": 137.0,
    "cp": 18.0,
    "ca": 0.24,
    "p": 0.324
  },
  {
    "id": "brewery_waste_tapioca",
    "name": "Brewery waste tapioca",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 5.0,
    "dm": 200.0,
    "tdn": 148.0,
    "cp": 10.0,
    "ca": 0.624,
    "p": 0.036
  },
  {
    "id": "mustard_oil",
    "name": "Mustard oil",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 80.0,
    "dm": 999.0,
    "tdn": 1940.0,
    "cp": 0.0,
    "ca": 0.0,
    "p": 0.0
  },
  {
    "id": "whole_pomegranate",
    "name": "Whole pomegranate",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 200.0,
    "tdn": 133.0,
    "cp": 83.4,
    "ca": 0.336,
    "p": 0.18
  },
  {
    "id": "vaal_bean",
    "name": "Vaal Bean",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 585.0,
    "cp": 231.0,
    "ca": 1.344,
    "p": 1.476
  },
  {
    "id": "tmr",
    "name": "TMR",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 10.0,
    "dm": 900.0,
    "tdn": 585.0,
    "cp": 140.0,
    "ca": 3.12,
    "p": 1.2
  },
  {
    "id": "niger_seed_cake",
    "name": "Niger Seed Cake",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 7.0,
    "dm": 900.0,
    "tdn": 450.0,
    "cp": 306.0,
    "ca": 1.08,
    "p": 1.296
  },
  {
    "id": "soybean_flakes",
    "name": "Soybean flakes",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 12.0,
    "dm": 900.0,
    "tdn": 566.0,
    "cp": 120.0,
    "ca": 3.84,
    "p": 0.96
  },
  {
    "id": "casia_tora_seeds",
    "name": "Casia Tora Seeds",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 495.0,
    "cp": 144.0,
    "ca": 3.24,
    "p": 1.188
  },
  {
    "id": "rubber_seed_cake",
    "name": "Rubber Seed Cake",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 495.0,
    "cp": 315.0,
    "ca": 4.212,
    "p": 2.7
  },
  {
    "id": "bypass_fat",
    "name": "Bypass Fat",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 120.0,
    "dm": 990.0,
    "tdn": 1855.0,
    "cp": 0.0,
    "ca": 96.0,
    "p": 0.0
  },
  {
    "id": "tapioca_meal",
    "name": "Tapioca Meal",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 5.0,
    "dm": 200.0,
    "tdn": 144.8,
    "cp": 1.0,
    "ca": 0.144,
    "p": 0.007
  },
  {
    "id": "neem_seed_cake",
    "name": "Neem Seed Cake",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 9.0,
    "dm": 900.0,
    "tdn": 495.0,
    "cp": 135.0,
    "ca": 2.916,
    "p": 0.756
  },
  {
    "id": "isabgol_lali",
    "name": "Isabgol (Lali)",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 20.0,
    "dm": 900.0,
    "tdn": 735.0,
    "cp": 290.0,
    "ca": 2.76,
    "p": 4.32
  },
  {
    "id": "mangoseed_kernal",
    "name": "Mangoseed Kernal",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 3.0,
    "dm": 900.0,
    "tdn": 495.0,
    "cp": 54.0,
    "ca": 1.08,
    "p": 0.864
  },
  {
    "id": "subabul_seeds",
    "name": "Subabul Seeds",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 585.0,
    "cp": 261.0,
    "ca": 1.944,
    "p": 1.188
  },
  {
    "id": "tapioca_peel",
    "name": "Tapioca Peel",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 5.0,
    "dm": 200.0,
    "tdn": 132.1,
    "cp": 7.46,
    "ca": 0.192,
    "p": 0.012
  },
  {
    "id": "cashewnut_waste",
    "name": "Cashewnut Waste",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 3.0,
    "dm": 900.0,
    "tdn": 450.0,
    "cp": 86.0,
    "ca": 1.512,
    "p": 0.972
  },
  {
    "id": "cocoa_pods",
    "name": "Cocoa pods",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 0.5,
    "dm": 900.0,
    "tdn": 572.0,
    "cp": 57.0,
    "ca": 2.462,
    "p": 1.102
  },
  {
    "id": "jack_fruit_seed",
    "name": "Jack Fruit Seed",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 4.0,
    "dm": 550.0,
    "tdn": 303.0,
    "cp": 66.0,
    "ca": 1.056,
    "p": 0.396
  },
  {
    "id": "barley_sprout",
    "name": "Barley Sprout",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 2.0,
    "dm": 300.0,
    "tdn": 180.0,
    "cp": 60.0,
    "ca": 0.576,
    "p": 0.432
  },
  {
    "id": "tomato_waste",
    "name": "Tomato Waste",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 0.75,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 30.0,
    "ca": 0.408,
    "p": 0.312
  },
  {
    "id": "biscuit_waste",
    "name": "Biscuit Waste",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 3.0,
    "dm": 900.0,
    "tdn": 820.0,
    "cp": 61.0,
    "ca": 0.24,
    "p": 0.24
  },
  {
    "id": "apple_pomace",
    "name": "Apple Pomace",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 0.75,
    "dm": 200.0,
    "tdn": 120.0,
    "cp": 24.0,
    "ca": 0.192,
    "p": 0.144
  },
  {
    "id": "tapioca_beer_waste___moist",
    "name": "Tapioca beer waste - Moist",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 5.0,
    "dm": 200.0,
    "tdn": 166.4,
    "cp": 14.44,
    "ca": 0.096,
    "p": 0.12
  },
  {
    "id": "whole_jack_fruit",
    "name": "Whole Jack Fruit",
    "group": "Other conc.",
    "category": "concentrate",
    "rate": 3.0,
    "dm": 220.0,
    "tdn": 110.0,
    "cp": 17.0,
    "ca": 0.372,
    "p": 0.084
  },
  {
    "id": "maize_cob_waste",
    "name": "Maize cob waste",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 0.8,
    "dm": 900.0,
    "tdn": 468.0,
    "cp": 20.0,
    "ca": 0.132,
    "p": 0.708
  },
  {
    "id": "banana_bunch_stalk",
    "name": "Banana Bunch Stalk",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 1.0,
    "dm": 900.0,
    "tdn": 366.0,
    "cp": 9.0,
    "ca": 0.18,
    "p": 0.132
  },
  {
    "id": "sugarcane_trash",
    "name": "Sugarcane trash",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 0.5,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 36.0,
    "ca": 0.348,
    "p": 1.176
  },
  {
    "id": "banana_roots",
    "name": "Banana Roots",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 1.0,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 24.0,
    "ca": 0.672,
    "p": 0.144
  },
  {
    "id": "banana_flowers",
    "name": "Banana Flowers",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 1.0,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 40.0,
    "ca": 0.48,
    "p": 0.216
  },
  {
    "id": "maize_sheeth",
    "name": "Maize Sheeth",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 2.0,
    "dm": 900.0,
    "tdn": 360.0,
    "cp": 18.0,
    "ca": 1.296,
    "p": 0.324
  },
  {
    "id": "banana_pseudo_stem",
    "name": "Banana pseudo stem",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 1.5,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 24.0,
    "ca": 0.864,
    "p": 0.144
  },
  {
    "id": "prosjuliflora_pods",
    "name": "Pros.juliflora pods",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 5.0,
    "dm": 900.0,
    "tdn": 585.0,
    "cp": 108.0,
    "ca": 1.944,
    "p": 0.54
  },
  {
    "id": "gnut_shell_powder",
    "name": "G.nut Shell powder",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 2.0,
    "dm": 900.0,
    "tdn": 342.0,
    "cp": 63.0,
    "ca": 1.08,
    "p": 0.216
  },
  {
    "id": "whole_sugarcane",
    "name": "Whole Sugarcane",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 1.5,
    "dm": 350.0,
    "tdn": 193.0,
    "cp": 7.0,
    "ca": 0.84,
    "p": 0.132
  },
  {
    "id": "cashew_apple",
    "name": "Cashew apple",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 1.0,
    "dm": 150.0,
    "tdn": 83.33,
    "cp": 18.98,
    "ca": 0.048,
    "p": 0.12
  },
  {
    "id": "cashew_apple_waste",
    "name": "Cashew apple waste",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 0.8,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 27.4,
    "ca": 0.6,
    "p": 0.816
  },
  {
    "id": "swt_potato_creepers",
    "name": "Swt. potato creepers",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 2.0,
    "dm": 150.0,
    "tdn": 60.0,
    "cp": 26.0,
    "ca": 1.296,
    "p": 0.144
  },
  {
    "id": "whole_carrot",
    "name": "Whole carrot",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 2.0,
    "dm": 150.0,
    "tdn": 123.0,
    "cp": 15.0,
    "ca": 0.288,
    "p": 0.192
  },
  {
    "id": "sugarcane_top_dry",
    "name": "Sugarcane top (dry)",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 1.0,
    "dm": 900.0,
    "tdn": 378.0,
    "cp": 28.0,
    "ca": 1.08,
    "p": 0.168
  },
  {
    "id": "cauliflower",
    "name": "Cauliflower",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 2.0,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 36.0,
    "ca": 3.744,
    "p": 0.408
  },
  {
    "id": "cabbage",
    "name": "Cabbage",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 2.0,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 38.0,
    "ca": 3.12,
    "p": 0.336
  },
  {
    "id": "sugarcane_bagasse",
    "name": "Sugarcane Bagasse",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 2.0,
    "dm": 800.0,
    "tdn": 280.0,
    "cp": 28.0,
    "ca": 1.536,
    "p": 0.288
  },
  {
    "id": "cotton_hulls",
    "name": "Cotton Hulls",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 2.0,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 108.0,
    "ca": 0.972,
    "p": 0.54
  },
  {
    "id": "banana_suckers",
    "name": "Banana Suckers",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 1.5,
    "dm": 200.0,
    "tdn": 100.0,
    "cp": 24.0,
    "ca": 0.864,
    "p": 0.144
  },
  {
    "id": "jackfruit_leaves",
    "name": "Jackfruit leaves",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 0.5,
    "dm": 400.0,
    "tdn": 240.0,
    "cp": 62.4,
    "ca": 0.276,
    "p": 0.048
  },
  {
    "id": "banana_peel",
    "name": "Banana peel",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 2.0,
    "dm": 100.0,
    "tdn": 114.0,
    "cp": 11.8,
    "ca": 1.392,
    "p": 0.6
  },
  {
    "id": "vaal_bean_plant",
    "name": "Vaal Bean Plant",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 1.0,
    "dm": 200.0,
    "tdn": 110.0,
    "cp": 46.8,
    "ca": 1.872,
    "p": 0.324
  },
  {
    "id": "rice_husk",
    "name": "Rice Husk",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 1.0,
    "dm": 900.0,
    "tdn": 250.0,
    "cp": 80.0,
    "ca": 0.24,
    "p": 1.404
  },
  {
    "id": "azolla",
    "name": "Azolla",
    "group": "Other roughage",
    "category": "roughage",
    "rate": 0.5,
    "dm": 60.0,
    "tdn": 42.0,
    "cp": 14.0,
    "ca": 0.072,
    "p": 0.036
  },
  {
    "id": "maize_silage",
    "name": "Maize silage",
    "group": "Silage",
    "category": "roughage",
    "rate": 1.0,
    "dm": 300.0,
    "tdn": 165.0,
    "cp": 24.0,
    "ca": 0.792,
    "p": 0.864
  },
  {
    "id": "oats_silage",
    "name": "Oats Silage",
    "group": "Silage",
    "category": "roughage",
    "rate": 1.0,
    "dm": 300.0,
    "tdn": 162.0,
    "cp": 24.0,
    "ca": 1.224,
    "p": 0.792
  },
  {
    "id": "hybrid_napier_silage",
    "name": "Hybrid Napier silage",
    "group": "Silage",
    "category": "roughage",
    "rate": 1.25,
    "dm": 300.0,
    "tdn": 165.0,
    "cp": 19.0,
    "ca": 1.728,
    "p": 0.648
  },
  {
    "id": "jowar_silage",
    "name": "Jowar Silage",
    "group": "Silage",
    "category": "roughage",
    "rate": 1.0,
    "dm": 300.0,
    "tdn": 150.0,
    "cp": 18.0,
    "ca": 0.864,
    "p": 0.684
  },
  {
    "id": "methi_straw",
    "name": "Methi straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 396.0,
    "cp": 64.0,
    "ca": 5.88,
    "p": 0.456
  },
  {
    "id": "gram_straw",
    "name": "Gram straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 487.0,
    "cp": 50.0,
    "ca": 6.192,
    "p": 0.504
  },
  {
    "id": "ragi_straw",
    "name": "Ragi Straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 3.5,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 31.0,
    "ca": 1.944,
    "p": 0.432
  },
  {
    "id": "dhania_straw",
    "name": "Dhania Straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 2.0,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 54.0,
    "ca": 1.728,
    "p": 0.324
  },
  {
    "id": "pulse_straw",
    "name": "Pulse Straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 3.5,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 36.0,
    "ca": 8.64,
    "p": 0.648
  },
  {
    "id": "mustard_straw",
    "name": "Mustard Straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 2.0,
    "dm": 900.0,
    "tdn": 360.0,
    "cp": 54.0,
    "ca": 1.512,
    "p": 0.324
  },
  {
    "id": "bajra_straw___stover",
    "name": "Bajra Straw / Stover",
    "group": "Straw",
    "category": "roughage",
    "rate": 3.5,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 32.0,
    "ca": 1.836,
    "p": 0.54
  },
  {
    "id": "pulse_pod_straw",
    "name": "Pulse pod straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 3.5,
    "dm": 900.0,
    "tdn": 450.0,
    "cp": 90.0,
    "ca": 5.28,
    "p": 0.54
  },
  {
    "id": "paddy_straw_urea_trtd",
    "name": "Paddy straw urea trtd.",
    "group": "Straw",
    "category": "roughage",
    "rate": 3.4,
    "dm": 850.0,
    "tdn": 383.0,
    "cp": 68.0,
    "ca": 1.632,
    "p": 0.312
  },
  {
    "id": "paddy_straw",
    "name": "Paddy Straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 3.0,
    "dm": 900.0,
    "tdn": 378.0,
    "cp": 41.0,
    "ca": 1.728,
    "p": 0.324
  },
  {
    "id": "wheat_straw_urea_treated",
    "name": "Wheat Straw Urea Treated",
    "group": "Straw",
    "category": "roughage",
    "rate": 4.4,
    "dm": 850.0,
    "tdn": 408.0,
    "cp": 43.0,
    "ca": 1.836,
    "p": 0.408
  },
  {
    "id": "groundnut_straw",
    "name": "Groundnut Straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 3.5,
    "dm": 900.0,
    "tdn": 432.0,
    "cp": 54.0,
    "ca": 7.668,
    "p": 0.54
  },
  {
    "id": "black_gram_straw",
    "name": "Black gram straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 2.5,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 80.0,
    "ca": 4.32,
    "p": 0.576
  },
  {
    "id": "red_gram_straw",
    "name": "Red gram straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 3.5,
    "dm": 900.0,
    "tdn": 410.0,
    "cp": 90.0,
    "ca": 2.88,
    "p": 0.432
  },
  {
    "id": "soyabean_straw",
    "name": "Soyabean Straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 3.0,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 45.0,
    "ca": 5.4,
    "p": 1.296
  },
  {
    "id": "jowar_straw___stover",
    "name": "Jowar Straw / Stover",
    "group": "Straw",
    "category": "roughage",
    "rate": 3.5,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 36.0,
    "ca": 2.7,
    "p": 0.432
  },
  {
    "id": "barley_straw",
    "name": "Barley Straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 3.0,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 36.0,
    "ca": 1.944,
    "p": 1.296
  },
  {
    "id": "wheat_straw",
    "name": "Wheat Straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 4.0,
    "dm": 900.0,
    "tdn": 396.0,
    "cp": 27.0,
    "ca": 1.944,
    "p": 0.432
  },
  {
    "id": "maize_straw___stover",
    "name": "Maize Straw / Stover",
    "group": "Straw",
    "category": "roughage",
    "rate": 3.5,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 36.0,
    "ca": 2.16,
    "p": 0.648
  },
  {
    "id": "guar_straw",
    "name": "Guar Straw",
    "group": "Straw",
    "category": "roughage",
    "rate": 3.5,
    "dm": 900.0,
    "tdn": 405.0,
    "cp": 117.0,
    "ca": 3.888,
    "p": 1.188
  }
];

export const FEED_BY_ID: Record<string, FeedItem> = Object.fromEntries(
  FEED_LIBRARY.map((f) => [f.id, f])
);

export function searchFeeds(query: string, category?: FeedCategory): FeedItem[] {
  const q = query.trim().toLowerCase();
  return FEED_LIBRARY.filter(
    (f) =>
      (!category || f.category === category) &&
      (!q || f.name.toLowerCase().includes(q) || f.group.toLowerCase().includes(q))
  );
}
